### PR TITLE
Update based on review

### PR DESCRIPTION
**Pull request by JunyiSun**

### CODE REVIEW

**Comment by JunyiSun** [comment]
Fixed #28 
External link : https://github.com/OpenLiberty/open-liberty/issues/2644

**Comment by lauracowen** [comment]
@JunyiSun It occurred to me to wonder why there is placeholder text at all if it's going to be replaced - maybe we should just be telling people to create the server.xml in this situation. I don't think that should hold up this PR though because I know this isn't the change you made. I thought I'd mention it though because it might be a useful consideration to make in new guides.

**Comment by yeekangc** [comment]
You are correct, @lauracowen.  I missed the change where empty file was added too.  Yes, this warrants a broader discussion in terms of our approach and design/style for the guides before we do it.  I'd improve the wording for now and make it clear what the users need to do.

We already have another issue under guides-common to look at what we should do in general to simplify the experience so users won't have to struggle with file creations unnecessarily.

**Comment by JunyiSun** [comment]
Hi @lauracowen, thank you for reviewing this PR. Yes, I agree we should be consistent with all other guides. Currently, we have a practice for other guides that we pre-create empty folders and have a `.gitkeep` file in them (GIT doesn't automatically commit any empty folders unless there is a file in it) , so that users/readers won't struggle with creating those nested folder structures and only need to create the Java file. Please review the latest changes and see if we can merge this PR. 

Thank you very much!

**Pull request merged**
