### PR TITLE
Ran Acrolinx and made some edits.

### PR DESCRIPTION
**Pull request by sishida**
I edited some typos and stuff after running Acrolinx.

Could someone also please look at this sentence:
"The desired Content-Type for a JSON response is application/json, using MediaType.APPLICATION_JSON instead of the String literal is better because in the event of a spelling error a compile failure will occur."
It didn't make sense to me, so I changed it and may have also accidentally changed the meaning. If you could check it for accuracy, that'd be great! Thank you!

### CODE REVIEW

**Comment by lauracowen** [comment]
That all looks fine except the removal of "let's". The slightly chatty style was intentionally kept for the guides.

**Comment by lauracowen** [comment]
Re the JSON, @yeekangc has raised a separate issue #12

**Comment by sishida** [comment]
Hi! Do we have an Open Liberty style guide or something that spells out how Open Liberty doc should be different from the "standard" IBM style? (I know we have a template and a sample doc, but sometimes I have difficulty inferring specific facts from a given example, and a list of rules/guidelines is clearer to me. From talking with my squad lead, I understood that the style differed when it came to things like using future tense, but I thought that we still wanted to avoid first person pronouns. Thank you!

**Comment by yeekangc** [comment]
@sishida, the references here are to the guides so I'd say we keep to what we have adopted for the guides.  OL documentation is a separate topic.  I will not confuse OL guides with OL documentation -- the guides aren't documentation.

We already have a template.  If necessary, we further spell out what we have in terms of style for the guides.  We can start with what you have and work with Laura and the team/community to refine them.

**Comment by yeekangc** [comment]
@sishida, we can start populating a style guide here:  https://github.com/OpenLiberty/guides-common/wiki

**Comment by sishida** [comment]
I put "let's" back in.

I also updated the wiki page: https://github.com/OpenLiberty/guides-common/wiki/Open-Liberty-Style-Guide Feel free to edit and add as you see fit.

Thank you!

**Pull request merged**
